language: go
go:
  #- 1.5  go test arguments are different in 1.5 :-(
  #- 1.6 issues with OSX release, and 1.7 is required now by core
  - 1.7
  - tip

go_import_path: k8s.io/kops

script:
  - make ci

